refactor sourcing of module.sh

diff --git a/fzf-fs b/fzf-fs
--- a/fzf-fs
+++ b/fzf-fs
@@ -36,7 +36,7 @@ if
 then
         builtin typeset -x FZF_FS_CONF_DIR="${FZF_FS_CONF_DIR:-${XDG_CONFIG_HOME:-${HOME}/.config}/fzf-fs.d}"
 else
-        builtin printf '%s\n' "fzf-fs:Error: Do not execute fzf-fs via source" 1>&2
+        builtin printf '%s\n' "fzf-fs: Error: Do not execute fzf-fs via source" 1>&2
         builtin return 1 2>/dev/null
 fi
 
@@ -1895,8 +1895,10 @@ KEYS
 Fzf::Fs::Main ()
 {
         builtin . "${FZF_FS_CONF_DIR}/keybinds.user" 2>/dev/null
-        builtin . "${FZF_FS_CONF_DIR}/get_keys.user" 2>/dev/null
-        builtin . "spath.sh"
+        builtin . "spath.sh" || {
+                        builtin printf '%s: Error: Could not source module: spath.sh\n' "${BASH_SOURCE[0]}" 1>&2
+                        builtin return 1
+        }
 
         [[ -d $FZF_FS_CONF_DIR && -d ${FZF_FS_SPOOL_FILE%/*} ]] || {
                 command mkdir -p \
